/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package driveingschool;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chiki
 */
public class firsttimelogin extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(firsttimelogin.class.getName());
    private String currentUsername;
    private String currentRole;
    private int currentUserId;
    private Connection con;

    /**
     * Creates new form firsttimelogin
     *
     * @param username the logged-in username
     * @param role     the logged-in user role
     * @param userId   the user_id from the users table
     */
    public firsttimelogin(String username, String role, int userId) {
        initComponents();
        this.currentUsername = (username != null) ? username : "";
        this.currentRole = (role != null) ? role : "";
        this.currentUserId = userId;

        lblWelcomeVal.setText(this.currentUsername);

        setLocationRelativeTo(null);
    }

    // -------------------------------------------------------------------------
    // DB helpers
    // -------------------------------------------------------------------------

    private Connection getConnection() {
        try {
            if (con == null || con.isClosed()) {
                con = DBConnection.connect();
            }
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
            con = DBConnection.connect();
        }
        return con;
    }

    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = md.digest(password.getBytes(StandardCharsets.UTF_8));
            return Base64.getEncoder().encodeToString(hashBytes);
        } catch (NoSuchAlgorithmException ex) {
            logger.log(Level.SEVERE, null, ex);
            return "";
        }
    }

    /** Marks first_time = 0 in the DB for this user (used by both actions). */
    private boolean markFirstTimeHandled() {
        Connection conn = getConnection();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection not available!", "Database Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String sql = "UPDATE users SET first_time = 0 WHERE user_id = ?";
        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setInt(1, currentUserId);
            return pst.executeUpdate() > 0;
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Failed to update first_time flag", ex);
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        lblWelcomeKey = new javax.swing.JLabel();
        lblWelcomeVal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNewPwd = new javax.swing.JLabel();
        txtNewPwd = new javax.swing.JPasswordField();
        lblConfirmPwd = new javax.swing.JLabel();
        txtConfirmPwd = new javax.swing.JPasswordField();
        btnChangePwd = new javax.swing.JButton();
        btnSkip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("First Time Login - Change Password");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(15, 23, 42));
        lblTitle.setText("First Time Login");

        lblSubTitle.setForeground(new java.awt.Color(100, 116, 139));
        lblSubTitle.setText("Please set a new password to continue.");

        lblWelcomeKey.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblWelcomeKey.setForeground(new java.awt.Color(51, 65, 85));
        lblWelcomeKey.setText("Welcome:");

        lblWelcomeVal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblWelcomeVal.setForeground(new java.awt.Color(37, 99, 235));
        lblWelcomeVal.setText("(username)");

        lblNewPwd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNewPwd.setForeground(new java.awt.Color(51, 65, 85));
        lblNewPwd.setText("New Password *");

        txtNewPwd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        lblConfirmPwd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblConfirmPwd.setForeground(new java.awt.Color(51, 65, 85));
        lblConfirmPwd.setText("Confirm Password *");

        txtConfirmPwd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnChangePwd.setBackground(new java.awt.Color(37, 99, 235));
        btnChangePwd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangePwd.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePwd.setText("Change Password");
        btnChangePwd.setBorder(null);
        btnChangePwd.setFocusPainted(false);
        btnChangePwd.addActionListener(this::btnChangePwdActionPerformed);

        btnSkip.setBackground(new java.awt.Color(100, 116, 139));
        btnSkip.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSkip.setForeground(new java.awt.Color(255, 255, 255));
        btnSkip.setText("Skip for Now");
        btnSkip.setBorder(null);
        btnSkip.setFocusPainted(false);
        btnSkip.addActionListener(this::btnSkipActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblSubTitle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWelcomeKey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWelcomeVal))
                    .addComponent(jSeparator1)
                    .addComponent(lblNewPwd)
                    .addComponent(txtNewPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(lblConfirmPwd)
                    .addComponent(txtConfirmPwd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcomeKey)
                    .addComponent(lblWelcomeVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblConfirmPwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // -------------------------------------------------------------------------
    // Event Handlers
    // -------------------------------------------------------------------------

    private void btnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePwdActionPerformed
        String newPassword = new String(txtNewPwd.getPassword()).trim();
        String confirmPassword = new String(txtConfirmPwd.getPassword()).trim();

        // --- Validation ---
        if (newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a new password!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtNewPwd.requestFocus();
            return;
        }
        if (newPassword.length() < 4) {
            JOptionPane.showMessageDialog(this, "Password must be at least 4 characters!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtNewPwd.requestFocus();
            return;
        }
        if (newPassword.length() > 50) {
            JOptionPane.showMessageDialog(this, "Password cannot exceed 50 characters!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtNewPwd.requestFocus();
            return;
        }
        if (confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please confirm your new password!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtConfirmPwd.requestFocus();
            return;
        }
        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtConfirmPwd.setText("");
            txtConfirmPwd.requestFocus();
            return;
        }

        // --- DB Update ---
        Connection conn = getConnection();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Cannot connect to the database!\nPlease check your MySQL server.", "Database Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String hashedPassword = hashPassword(newPassword);
        String sql = "UPDATE users SET password = ?, first_time = 0 WHERE user_id = ?";
        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, hashedPassword);
            pst.setInt(2, currentUserId);
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this,
                    "Password changed successfully!\nYou can now use your new password to log in.",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                new Dashbord(currentUsername, currentRole).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update password. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Failed to change password", ex);
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChangePwdActionPerformed

    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to skip?\n\nYou are currently using the default password.\nIt is strongly recommended to change it for security.",
            "Skip Password Change", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            // Mark first_time = 0 so user is not prompted every login
            markFirstTimeHandled();
            new Dashbord(currentUsername, currentRole).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSkipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        FlatLafSetup.setup();
        java.awt.EventQueue.invokeLater(() -> new firsttimelogin("TestUser", "Staff", 1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePwd;
    private javax.swing.JButton btnSkip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfirmPwd;
    private javax.swing.JLabel lblNewPwd;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcomeKey;
    private javax.swing.JLabel lblWelcomeVal;
    private javax.swing.JPasswordField txtConfirmPwd;
    private javax.swing.JPasswordField txtNewPwd;
    // End of variables declaration//GEN-END:variables
}
